name: maven_buidl_verify

on:
  workflow_call:
    inputs:
      cmd:
        type: string
        required: false
        default: "mvn -B --update-snapshots javadoc:javadoc verify site"
        description: "The full mvn command to run."

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: ${{ inputs.cmd }}
