name: maven

on:
  push:

jobs:
  build_and_verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn -B --update-snapshots verify javadoc:javadoc site
