name: maven_publish

on:
  push:
    branches:
      - main
      - seattle
    paths-ignore:
      - "**/*.md"
      - "src/test/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  publish:
    uses: jiaqi/cyclopsgroup/.github/workflows/maven-publish.yml@seattle
