name: maven_verify

on:
  push:
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build_and_verify:
    uses: jiaqi/cyclopsgroup/.github/workflows/maven-verify.yml@seattle
