name: maven

on:
  push:

jobs:
  build_and_verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn -B --update-snapshots verify javadoc:javadoc site
  publish:
    needs: build_and_verify
    if: contains(fromJSON('["main", "seattle"]'), github.ref_name)
    permissions:
      contents: read
      pages: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn -B package javadoc:javadoc site
    - name: Deploy SNAPSHOT package
      run: mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: target/site
    - name: Deploy site
      uses: actions/deploy-pages@v4
